---
# $ ansible-galaxy install geerlingguy.pip
# $ ansible-galaxy install geerlingguy.docker

- name: Install Docker and docker-compose
  hosts: all
  gather_facts: yes
  become: true

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

  pre_tasks:
    - apt:
        name: python3-pip
        state: present

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
...