# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "nostromo" => "10.0.0.10",
  "galactica" => "10.0.0.11",
  "enterprise" => "10.0.0.12"
}

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    hosts.each do |name, ip|
        config.vm.define name do |machine|
            machine.vm.network :private_network, ip: ip
            machine.vm.hostname = name
            machine.vm.provider "virtualbox" do |v|
                v.name = name
                v.memory = 1024
                v.cpus = 1
            end

            config.vm.provision "shell", inline: <<-SHELL
                sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                systemctl restart sshd.service
            SHELL

        end
    end
end